### ISSUE TITLE
Missing step to build client code in README?

### ISSUE THREAD

**Issue by shaaraddalvi** [andykitt/waterIntake#1]
First of all thanks for the app with awesome UI!

While trying to build the app locally I had to run 

```
npm install
npm run client-install
```
Post that we need to run `npm run build --prefix client` before starting the server which is only part of `heroku-postbuild` and not mentioned anywhere in the README. 

Happy to make changes to the README and raise a pull request.

**Comment by tinypell3ts** [comment]
Hey,

Thanks 😊 I haven't ran this for a long time. if you could create a pull request that would be great. 👍
